version: "3.9"

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - default

  postgres:
    image: postgres:13
    ports:
      - "7777:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: twt
      POSTGRES_PASSWORD: twt
      POSTGRES_DB: twt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      POSTGRES_URI: postgres://twt:twt@postgres:5432/twt
      REDIS_URI: redis://redis
    networks:
      - default

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    name: twt
